controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

app_confirm_email:
    path: /confirm-email/{token}
    controller: App\Controller\EmailConfirmationController::confirmEmail


