controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

api_fetch:
    path: /api/velib
    controller: App\Controller\ApiController::fetchVelibData

